<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260128222636 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE activites_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE annee_pastorale_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bilan_treso_event_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE branche_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE caisse_activite_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE caisse_groupe_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE commissariat_district_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE details_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE documents_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE evenement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exercer_fonction_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE fonction_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE formation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE genre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE groupe_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maitrise_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mouvement_entite_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mouvement_groupe_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mouvement_treso_activite_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE periode_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE region_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE responsable_formation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE rubrique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE rubrique_budget_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sens_rubrique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE session_formation_responsable_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sous_rubrique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tresorerie_activite_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_document_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_mouvement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE utilisateur_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE activites (id INT NOT NULL, groupe_id INT DEFAULT NULL, branche_id INT DEFAULT NULL, anneepastorale_id INT NOT NULL, description VARCHAR(500) DEFAULT NULL, localisation VARCHAR(500) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, commune VARCHAR(255) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, heure_debut TIME(0) WITHOUT TIME ZONE DEFAULT NULL, heure_fin TIME(0) WITHOUT TIME ZONE DEFAULT NULL, statut INT NOT NULL, autorisation VARCHAR(255) DEFAULT NULL, nbre_participant INT NOT NULL, prix INT NOT NULL, nom VARCHAR(255) NOT NULL, commentaire VARCHAR(255) DEFAULT NULL, date_validation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_creation VARCHAR(255) DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_modification VARCHAR(255) DEFAULT NULL, bactif BOOLEAN NOT NULL, cible VARCHAR(255) NOT NULL, b_one_day BOOLEAN NOT NULL, b_soumis BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_766B5EB57A45358C ON activites (groupe_id)');
        $this->addSql('CREATE INDEX IDX_766B5EB59DDF9A9E ON activites (branche_id)');
        $this->addSql('CREATE INDEX IDX_766B5EB5ED0F89B8 ON activites (anneepastorale_id)');
        $this->addSql('CREATE TABLE annee_pastorale (id INT NOT NULL, code_annee VARCHAR(15) NOT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL, b_actif BOOLEAN NOT NULL, date_creation DATE DEFAULT NULL, user_creation VARCHAR(255) DEFAULT NULL, date_modification DATE DEFAULT NULL, user_modification VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE bilan_treso_event (id INT NOT NULL, event_id INT NOT NULL, total_credit BIGINT NOT NULL, total_debit BIGINT NOT NULL, date_bilan TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_creation INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE branche (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, tranche_age VARCHAR(255) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_creation VARCHAR(255) DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_modification VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE caisse_activite (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE caisse_groupe (id INT NOT NULL, groupe_id INT NOT NULL, datecreate TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datemodification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, usercreate INT DEFAULT NULL, user_modification INT DEFAULT NULL, solde BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_89EA3407A45358C ON caisse_groupe (groupe_id)');
        $this->addSql('CREATE TABLE commissariat_district (id INT NOT NULL, nom VARCHAR(255) NOT NULL, nickname VARCHAR(255) DEFAULT NULL, datecreation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, usercreation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, telephone VARCHAR(15) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE cotisation (id UUID NOT NULL, jeune_id UUID DEFAULT NULL, responsable_id UUID DEFAULT NULL, annee_pastorale_id INT NOT NULL, matricule VARCHAR(20) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_creation VARCHAR(255) DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_modification VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AE64D2ED15924E15 ON cotisation (jeune_id)');
        $this->addSql('CREATE INDEX IDX_AE64D2ED53C59D72 ON cotisation (responsable_id)');
        $this->addSql('CREATE INDEX IDX_AE64D2ED6E32D7DB ON cotisation (annee_pastorale_id)');
        $this->addSql('CREATE TABLE details (id INT NOT NULL, branche_id INT DEFAULT NULL, activite_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, deroulement VARCHAR(500) DEFAULT NULL, date DATE NOT NULL, heuredebut TIME(0) WITHOUT TIME ZONE NOT NULL, heure_fin TIME(0) WITHOUT TIME ZONE NOT NULL, cible VARCHAR(255) NOT NULL, objectif VARCHAR(500) DEFAULT NULL, impact VARCHAR(500) DEFAULT NULL, statut INT NOT NULL, commentaire VARCHAR(500) DEFAULT NULL, bactif BOOLEAN NOT NULL, user_creation INT DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_modification INT DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, responsable_activite VARCHAR(255) DEFAULT NULL, fonction VARCHAR(255) DEFAULT NULL, contact VARCHAR(15) DEFAULT NULL, date_validation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_72260B8A9DDF9A9E ON details (branche_id)');
        $this->addSql('CREATE INDEX IDX_72260B8A9B0F88B1 ON details (activite_id)');
        $this->addSql('CREATE TABLE district (id UUID NOT NULL, user_id INT DEFAULT NULL, commissariat_district_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, prenoms VARCHAR(255) NOT NULL, dob VARCHAR(255) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_creation VARCHAR(255) DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_modification VARCHAR(255) DEFAULT NULL, telephone VARCHAR(10) DEFAULT NULL, email VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_31C15487A76ED395 ON district (user_id)');
        $this->addSql('CREATE INDEX IDX_31C154876066AA10 ON district (commissariat_district_id)');
        $this->addSql('CREATE TABLE documents (id INT NOT NULL, type_document_id INT NOT NULL, activite_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, extension VARCHAR(255) DEFAULT NULL, directory_path VARCHAR(255) NOT NULL, date_create TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_creation VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A2B072888826AFA6 ON documents (type_document_id)');
        $this->addSql('CREATE INDEX IDX_A2B072889B0F88B1 ON documents (activite_id)');
        $this->addSql('CREATE TABLE evenement (id INT NOT NULL, libelle VARCHAR(50) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_creation INT NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_modification INT DEFAULT NULL, entite INT NOT NULL, id_entite INT NOT NULL, statut SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE exercer_fonction (id INT NOT NULL, annee_pastorale_id INT DEFAULT NULL, responsable_id UUID DEFAULT NULL, fonction_id INT DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_creation VARCHAR(255) DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_modification VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F99A70306E32D7DB ON exercer_fonction (annee_pastorale_id)');
        $this->addSql('CREATE INDEX IDX_F99A703053C59D72 ON exercer_fonction (responsable_id)');
        $this->addSql('CREATE INDEX IDX_F99A703057889920 ON exercer_fonction (fonction_id)');
        $this->addSql('CREATE TABLE exercer_fonction_district (exercer_fonction_id INT NOT NULL, district_id UUID NOT NULL, PRIMARY KEY(exercer_fonction_id, district_id))');
        $this->addSql('CREATE INDEX IDX_E44521067DCF23F5 ON exercer_fonction_district (exercer_fonction_id)');
        $this->addSql('CREATE INDEX IDX_E4452106B08FA272 ON exercer_fonction_district (district_id)');
        $this->addSql('CREATE TABLE fonction (id INT NOT NULL, code VARCHAR(255) NOT NULL, libelle VARCHAR(255) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_modification VARCHAR(255) DEFAULT NULL, role VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE formation (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, ordre INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE formation_responsable (formation_id INT NOT NULL, responsable_id UUID NOT NULL, PRIMARY KEY(formation_id, responsable_id))');
        $this->addSql('CREATE INDEX IDX_DAF2DDC5200282E ON formation_responsable (formation_id)');
        $this->addSql('CREATE INDEX IDX_DAF2DDC53C59D72 ON formation_responsable (responsable_id)');
        $this->addSql('CREATE TABLE genre (id INT NOT NULL, libelle VARCHAR(15) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE groupe (id INT NOT NULL, commissariat_district_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, nick_name VARCHAR(255) NOT NULL, phone1 VARCHAR(15) DEFAULT NULL, phone2 VARCHAR(15) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, slogan VARCHAR(255) DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_creation VARCHAR(255) DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_modification VARCHAR(255) DEFAULT NULL, paroisse VARCHAR(255) NOT NULL, region VARCHAR(255) NOT NULL, filename VARCHAR(255) DEFAULT NULL, extension VARCHAR(255) DEFAULT NULL, filebase VARCHAR(255) DEFAULT NULL, filebasetext TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4B98C216066AA10 ON groupe (commissariat_district_id)');
        $this->addSql('CREATE TABLE inscription (id UUID NOT NULL, jeunes_id UUID NOT NULL, annee_id INT NOT NULL, date_inscription TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E90F6D68AB9CB80 ON inscription (jeunes_id)');
        $this->addSql('CREATE INDEX IDX_5E90F6D6543EC5F0 ON inscription (annee_id)');
        $this->addSql('CREATE TABLE jeune (id UUID NOT NULL, branche_id INT DEFAULT NULL, groupe_id INT NOT NULL, genre_id INT NOT NULL, nom VARCHAR(255) NOT NULL, prenoms VARCHAR(255) NOT NULL, dob DATE NOT NULL, lieu_habitation VARCHAR(255) DEFAULT NULL, occupation VARCHAR(255) DEFAULT NULL, nom_pere VARCHAR(255) DEFAULT NULL, num_pere VARCHAR(255) DEFAULT NULL, nom_mere VARCHAR(255) DEFAULT NULL, num_mere VARCHAR(255) DEFAULT NULL, matricule VARCHAR(255) DEFAULT NULL, statut INT NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_creation VARCHAR(255) NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_modification VARCHAR(255) DEFAULT NULL, telephone VARCHAR(15) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8DC4E6859DDF9A9E ON jeune (branche_id)');
        $this->addSql('CREATE INDEX IDX_8DC4E6857A45358C ON jeune (groupe_id)');
        $this->addSql('CREATE INDEX IDX_8DC4E6854296D31F ON jeune (genre_id)');
        $this->addSql('CREATE TABLE maitrise (id INT NOT NULL, activite_id INT DEFAULT NULL, relation_id UUID DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_creation VARCHAR(255) DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, bactif BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9F5E12959B0F88B1 ON maitrise (activite_id)');
        $this->addSql('CREATE INDEX IDX_9F5E12953256915B ON maitrise (relation_id)');
        $this->addSql('CREATE TABLE mouvement_entite (id INT NOT NULL, periode_id INT NOT NULL, sousrubrique_id INT NOT NULL, datemvt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, montant BIGINT NOT NULL, description VARCHAR(255) NOT NULL, entite_id INT NOT NULL, usermvt INT NOT NULL, entite SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_60699611F384C1CF ON mouvement_entite (periode_id)');
        $this->addSql('CREATE INDEX IDX_60699611BEE02DA1 ON mouvement_entite (sousrubrique_id)');
        $this->addSql('CREATE TABLE mouvement_groupe (id INT NOT NULL, groupe_id INT DEFAULT NULL, periode_id INT DEFAULT NULL, caisse_id INT DEFAULT NULL, typemouvement_id INT DEFAULT NULL, datemouvement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, montant BIGINT NOT NULL, datecreate TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usercreate INT NOT NULL, datemodification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, usermodification INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7EF902177A45358C ON mouvement_groupe (groupe_id)');
        $this->addSql('CREATE INDEX IDX_7EF90217F384C1CF ON mouvement_groupe (periode_id)');
        $this->addSql('CREATE INDEX IDX_7EF9021727B4FEBF ON mouvement_groupe (caisse_id)');
        $this->addSql('CREATE INDEX IDX_7EF90217F975A74D ON mouvement_groupe (typemouvement_id)');
        $this->addSql('CREATE TABLE mouvement_treso_activite (id INT NOT NULL, sous_rubrique_id INT NOT NULL, periode_id INT NOT NULL, montant BIGINT NOT NULL, date_mouvement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_id INT NOT NULL, commentaire VARCHAR(50) DEFAULT NULL, user_creation SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5800C1CD7BEAFB00 ON mouvement_treso_activite (sous_rubrique_id)');
        $this->addSql('CREATE INDEX IDX_5800C1CDF384C1CF ON mouvement_treso_activite (periode_id)');
        $this->addSql('CREATE TABLE periode (id INT NOT NULL, anneepastorale_id INT NOT NULL, datedebut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datefin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, etat INT NOT NULL, datecreate TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datemodification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, usercreate INT NOT NULL, usermodification INT DEFAULT NULL, code VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_93C32DF3ED0F89B8 ON periode (anneepastorale_id)');
        $this->addSql('CREATE TABLE region (id INT NOT NULL, nom VARCHAR(255) NOT NULL, nickname VARCHAR(255) NOT NULL, datecreation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, usercreation VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE responsable (id UUID NOT NULL, groupe_id INT DEFAULT NULL, genre_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, prenoms VARCHAR(255) NOT NULL, dob DATE NOT NULL, habitation VARCHAR(255) NOT NULL, occupation VARCHAR(255) NOT NULL, telephone VARCHAR(20) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_creation VARCHAR(255) NOT NULL, date_modification VARCHAR(255) DEFAULT NULL, user_modification VARCHAR(255) DEFAULT NULL, statut INT NOT NULL, email VARCHAR(100) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_52520D077A45358C ON responsable (groupe_id)');
        $this->addSql('CREATE INDEX IDX_52520D074296D31F ON responsable (genre_id)');
        $this->addSql('CREATE TABLE responsable_formation (id INT NOT NULL, responsable_id_id UUID NOT NULL, formation_id_id INT NOT NULL, datecreation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, dateformation VARCHAR(255) DEFAULT NULL, lieu VARCHAR(255) DEFAULT NULL, identification VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BD0670A91ED5BB35 ON responsable_formation (responsable_id_id)');
        $this->addSql('CREATE INDEX IDX_BD0670A99CF0022 ON responsable_formation (formation_id_id)');
        $this->addSql('CREATE TABLE rubrique (id INT NOT NULL, code VARCHAR(50) NOT NULL, libelle VARCHAR(50) NOT NULL, sens VARCHAR(1) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE rubrique_budget (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, bactif BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE sens_rubrique (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, sens VARCHAR(1) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE session_formation (id UUID NOT NULL, stage_formation_id INT NOT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL, directeur_stage VARCHAR(255) DEFAULT NULL, lieu VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3A264B5120ED475 ON session_formation (stage_formation_id)');
        $this->addSql('CREATE TABLE session_formation_responsable (id INT NOT NULL, session_id_id UUID DEFAULT NULL, responsable_id_id UUID DEFAULT NULL, ref_diplome VARCHAR(50) DEFAULT NULL, bconfirm_pariticpation BOOLEAN DEFAULT NULL, binscrit BOOLEAN NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_948F929EA4392681 ON session_formation_responsable (session_id_id)');
        $this->addSql('CREATE INDEX IDX_948F929E1ED5BB35 ON session_formation_responsable (responsable_id_id)');
        $this->addSql('CREATE TABLE sous_rubrique (id INT NOT NULL, rubrique_id INT NOT NULL, code VARCHAR(50) NOT NULL, libelle VARCHAR(50) NOT NULL, type INT DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_creation INT DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_modification INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_87EA3D293BD38833 ON sous_rubrique (rubrique_id)');
        $this->addSql('CREATE TABLE tresorerie_activite (id INT NOT NULL, event_id INT NOT NULL, solde BIGINT NOT NULL, date_solde TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_creation INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_document (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, date_create TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, bactif BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_mouvement (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, code VARCHAR(1) NOT NULL, datecreate TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usercreate INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "user" (id INT NOT NULL, groupe_id INT DEFAULT NULL, responsable_id UUID NOT NULL, district_id UUID DEFAULT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_creation VARCHAR(255) NOT NULL, b_actif BOOLEAN NOT NULL, first_connection BOOLEAN NOT NULL, last_connection TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE INDEX IDX_8D93D6497A45358C ON "user" (groupe_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64953C59D72 ON "user" (responsable_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649B08FA272 ON "user" (district_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT NOT NULL, responsable_id UUID DEFAULT NULL, password VARCHAR(255) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_creation VARCHAR(255) NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, username VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B353C59D72 ON utilisateur (responsable_id)');
        $this->addSql('ALTER TABLE activites ADD CONSTRAINT FK_766B5EB57A45358C FOREIGN KEY (groupe_id) REFERENCES groupe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE activites ADD CONSTRAINT FK_766B5EB59DDF9A9E FOREIGN KEY (branche_id) REFERENCES branche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE activites ADD CONSTRAINT FK_766B5EB5ED0F89B8 FOREIGN KEY (anneepastorale_id) REFERENCES annee_pastorale (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE caisse_groupe ADD CONSTRAINT FK_89EA3407A45358C FOREIGN KEY (groupe_id) REFERENCES groupe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cotisation ADD CONSTRAINT FK_AE64D2ED15924E15 FOREIGN KEY (jeune_id) REFERENCES jeune (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cotisation ADD CONSTRAINT FK_AE64D2ED53C59D72 FOREIGN KEY (responsable_id) REFERENCES responsable (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cotisation ADD CONSTRAINT FK_AE64D2ED6E32D7DB FOREIGN KEY (annee_pastorale_id) REFERENCES annee_pastorale (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE details ADD CONSTRAINT FK_72260B8A9DDF9A9E FOREIGN KEY (branche_id) REFERENCES branche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE details ADD CONSTRAINT FK_72260B8A9B0F88B1 FOREIGN KEY (activite_id) REFERENCES activites (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE district ADD CONSTRAINT FK_31C15487A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE district ADD CONSTRAINT FK_31C154876066AA10 FOREIGN KEY (commissariat_district_id) REFERENCES commissariat_district (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_A2B072888826AFA6 FOREIGN KEY (type_document_id) REFERENCES type_document (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_A2B072889B0F88B1 FOREIGN KEY (activite_id) REFERENCES activites (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exercer_fonction ADD CONSTRAINT FK_F99A70306E32D7DB FOREIGN KEY (annee_pastorale_id) REFERENCES annee_pastorale (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exercer_fonction ADD CONSTRAINT FK_F99A703053C59D72 FOREIGN KEY (responsable_id) REFERENCES responsable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exercer_fonction ADD CONSTRAINT FK_F99A703057889920 FOREIGN KEY (fonction_id) REFERENCES fonction (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exercer_fonction_district ADD CONSTRAINT FK_E44521067DCF23F5 FOREIGN KEY (exercer_fonction_id) REFERENCES exercer_fonction (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exercer_fonction_district ADD CONSTRAINT FK_E4452106B08FA272 FOREIGN KEY (district_id) REFERENCES district (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE formation_responsable ADD CONSTRAINT FK_DAF2DDC5200282E FOREIGN KEY (formation_id) REFERENCES formation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE formation_responsable ADD CONSTRAINT FK_DAF2DDC53C59D72 FOREIGN KEY (responsable_id) REFERENCES responsable (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE groupe ADD CONSTRAINT FK_4B98C216066AA10 FOREIGN KEY (commissariat_district_id) REFERENCES commissariat_district (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT FK_5E90F6D68AB9CB80 FOREIGN KEY (jeunes_id) REFERENCES jeune (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT FK_5E90F6D6543EC5F0 FOREIGN KEY (annee_id) REFERENCES annee_pastorale (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jeune ADD CONSTRAINT FK_8DC4E6859DDF9A9E FOREIGN KEY (branche_id) REFERENCES branche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jeune ADD CONSTRAINT FK_8DC4E6857A45358C FOREIGN KEY (groupe_id) REFERENCES groupe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE jeune ADD CONSTRAINT FK_8DC4E6854296D31F FOREIGN KEY (genre_id) REFERENCES genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE maitrise ADD CONSTRAINT FK_9F5E12959B0F88B1 FOREIGN KEY (activite_id) REFERENCES activites (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE maitrise ADD CONSTRAINT FK_9F5E12953256915B FOREIGN KEY (relation_id) REFERENCES responsable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement_entite ADD CONSTRAINT FK_60699611F384C1CF FOREIGN KEY (periode_id) REFERENCES periode (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement_entite ADD CONSTRAINT FK_60699611BEE02DA1 FOREIGN KEY (sousrubrique_id) REFERENCES sous_rubrique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement_groupe ADD CONSTRAINT FK_7EF902177A45358C FOREIGN KEY (groupe_id) REFERENCES groupe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement_groupe ADD CONSTRAINT FK_7EF90217F384C1CF FOREIGN KEY (periode_id) REFERENCES periode (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement_groupe ADD CONSTRAINT FK_7EF9021727B4FEBF FOREIGN KEY (caisse_id) REFERENCES caisse_groupe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement_groupe ADD CONSTRAINT FK_7EF90217F975A74D FOREIGN KEY (typemouvement_id) REFERENCES type_mouvement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement_treso_activite ADD CONSTRAINT FK_5800C1CD7BEAFB00 FOREIGN KEY (sous_rubrique_id) REFERENCES sous_rubrique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mouvement_treso_activite ADD CONSTRAINT FK_5800C1CDF384C1CF FOREIGN KEY (periode_id) REFERENCES periode (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE periode ADD CONSTRAINT FK_93C32DF3ED0F89B8 FOREIGN KEY (anneepastorale_id) REFERENCES annee_pastorale (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE responsable ADD CONSTRAINT FK_52520D077A45358C FOREIGN KEY (groupe_id) REFERENCES groupe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE responsable ADD CONSTRAINT FK_52520D074296D31F FOREIGN KEY (genre_id) REFERENCES genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE responsable_formation ADD CONSTRAINT FK_BD0670A91ED5BB35 FOREIGN KEY (responsable_id_id) REFERENCES responsable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE responsable_formation ADD CONSTRAINT FK_BD0670A99CF0022 FOREIGN KEY (formation_id_id) REFERENCES formation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE session_formation ADD CONSTRAINT FK_3A264B5120ED475 FOREIGN KEY (stage_formation_id) REFERENCES formation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE session_formation_responsable ADD CONSTRAINT FK_948F929EA4392681 FOREIGN KEY (session_id_id) REFERENCES session_formation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE session_formation_responsable ADD CONSTRAINT FK_948F929E1ED5BB35 FOREIGN KEY (responsable_id_id) REFERENCES responsable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sous_rubrique ADD CONSTRAINT FK_87EA3D293BD38833 FOREIGN KEY (rubrique_id) REFERENCES rubrique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6497A45358C FOREIGN KEY (groupe_id) REFERENCES groupe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64953C59D72 FOREIGN KEY (responsable_id) REFERENCES responsable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649B08FA272 FOREIGN KEY (district_id) REFERENCES district (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B353C59D72 FOREIGN KEY (responsable_id) REFERENCES responsable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE activites_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE annee_pastorale_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bilan_treso_event_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE branche_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE caisse_activite_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE caisse_groupe_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE commissariat_district_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE details_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE documents_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE evenement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exercer_fonction_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE fonction_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE formation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE genre_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE groupe_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maitrise_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mouvement_entite_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mouvement_groupe_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mouvement_treso_activite_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE periode_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE region_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE responsable_formation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE rubrique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE rubrique_budget_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sens_rubrique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE session_formation_responsable_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sous_rubrique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tresorerie_activite_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_document_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_mouvement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE utilisateur_id_seq CASCADE');
        $this->addSql('ALTER TABLE activites DROP CONSTRAINT FK_766B5EB57A45358C');
        $this->addSql('ALTER TABLE activites DROP CONSTRAINT FK_766B5EB59DDF9A9E');
        $this->addSql('ALTER TABLE activites DROP CONSTRAINT FK_766B5EB5ED0F89B8');
        $this->addSql('ALTER TABLE caisse_groupe DROP CONSTRAINT FK_89EA3407A45358C');
        $this->addSql('ALTER TABLE cotisation DROP CONSTRAINT FK_AE64D2ED15924E15');
        $this->addSql('ALTER TABLE cotisation DROP CONSTRAINT FK_AE64D2ED53C59D72');
        $this->addSql('ALTER TABLE cotisation DROP CONSTRAINT FK_AE64D2ED6E32D7DB');
        $this->addSql('ALTER TABLE details DROP CONSTRAINT FK_72260B8A9DDF9A9E');
        $this->addSql('ALTER TABLE details DROP CONSTRAINT FK_72260B8A9B0F88B1');
        $this->addSql('ALTER TABLE district DROP CONSTRAINT FK_31C15487A76ED395');
        $this->addSql('ALTER TABLE district DROP CONSTRAINT FK_31C154876066AA10');
        $this->addSql('ALTER TABLE documents DROP CONSTRAINT FK_A2B072888826AFA6');
        $this->addSql('ALTER TABLE documents DROP CONSTRAINT FK_A2B072889B0F88B1');
        $this->addSql('ALTER TABLE exercer_fonction DROP CONSTRAINT FK_F99A70306E32D7DB');
        $this->addSql('ALTER TABLE exercer_fonction DROP CONSTRAINT FK_F99A703053C59D72');
        $this->addSql('ALTER TABLE exercer_fonction DROP CONSTRAINT FK_F99A703057889920');
        $this->addSql('ALTER TABLE exercer_fonction_district DROP CONSTRAINT FK_E44521067DCF23F5');
        $this->addSql('ALTER TABLE exercer_fonction_district DROP CONSTRAINT FK_E4452106B08FA272');
        $this->addSql('ALTER TABLE formation_responsable DROP CONSTRAINT FK_DAF2DDC5200282E');
        $this->addSql('ALTER TABLE formation_responsable DROP CONSTRAINT FK_DAF2DDC53C59D72');
        $this->addSql('ALTER TABLE groupe DROP CONSTRAINT FK_4B98C216066AA10');
        $this->addSql('ALTER TABLE inscription DROP CONSTRAINT FK_5E90F6D68AB9CB80');
        $this->addSql('ALTER TABLE inscription DROP CONSTRAINT FK_5E90F6D6543EC5F0');
        $this->addSql('ALTER TABLE jeune DROP CONSTRAINT FK_8DC4E6859DDF9A9E');
        $this->addSql('ALTER TABLE jeune DROP CONSTRAINT FK_8DC4E6857A45358C');
        $this->addSql('ALTER TABLE jeune DROP CONSTRAINT FK_8DC4E6854296D31F');
        $this->addSql('ALTER TABLE maitrise DROP CONSTRAINT FK_9F5E12959B0F88B1');
        $this->addSql('ALTER TABLE maitrise DROP CONSTRAINT FK_9F5E12953256915B');
        $this->addSql('ALTER TABLE mouvement_entite DROP CONSTRAINT FK_60699611F384C1CF');
        $this->addSql('ALTER TABLE mouvement_entite DROP CONSTRAINT FK_60699611BEE02DA1');
        $this->addSql('ALTER TABLE mouvement_groupe DROP CONSTRAINT FK_7EF902177A45358C');
        $this->addSql('ALTER TABLE mouvement_groupe DROP CONSTRAINT FK_7EF90217F384C1CF');
        $this->addSql('ALTER TABLE mouvement_groupe DROP CONSTRAINT FK_7EF9021727B4FEBF');
        $this->addSql('ALTER TABLE mouvement_groupe DROP CONSTRAINT FK_7EF90217F975A74D');
        $this->addSql('ALTER TABLE mouvement_treso_activite DROP CONSTRAINT FK_5800C1CD7BEAFB00');
        $this->addSql('ALTER TABLE mouvement_treso_activite DROP CONSTRAINT FK_5800C1CDF384C1CF');
        $this->addSql('ALTER TABLE periode DROP CONSTRAINT FK_93C32DF3ED0F89B8');
        $this->addSql('ALTER TABLE responsable DROP CONSTRAINT FK_52520D077A45358C');
        $this->addSql('ALTER TABLE responsable DROP CONSTRAINT FK_52520D074296D31F');
        $this->addSql('ALTER TABLE responsable_formation DROP CONSTRAINT FK_BD0670A91ED5BB35');
        $this->addSql('ALTER TABLE responsable_formation DROP CONSTRAINT FK_BD0670A99CF0022');
        $this->addSql('ALTER TABLE session_formation DROP CONSTRAINT FK_3A264B5120ED475');
        $this->addSql('ALTER TABLE session_formation_responsable DROP CONSTRAINT FK_948F929EA4392681');
        $this->addSql('ALTER TABLE session_formation_responsable DROP CONSTRAINT FK_948F929E1ED5BB35');
        $this->addSql('ALTER TABLE sous_rubrique DROP CONSTRAINT FK_87EA3D293BD38833');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6497A45358C');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64953C59D72');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649B08FA272');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B353C59D72');
        $this->addSql('DROP TABLE activites');
        $this->addSql('DROP TABLE annee_pastorale');
        $this->addSql('DROP TABLE bilan_treso_event');
        $this->addSql('DROP TABLE branche');
        $this->addSql('DROP TABLE caisse_activite');
        $this->addSql('DROP TABLE caisse_groupe');
        $this->addSql('DROP TABLE commissariat_district');
        $this->addSql('DROP TABLE cotisation');
        $this->addSql('DROP TABLE details');
        $this->addSql('DROP TABLE district');
        $this->addSql('DROP TABLE documents');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE exercer_fonction');
        $this->addSql('DROP TABLE exercer_fonction_district');
        $this->addSql('DROP TABLE fonction');
        $this->addSql('DROP TABLE formation');
        $this->addSql('DROP TABLE formation_responsable');
        $this->addSql('DROP TABLE genre');
        $this->addSql('DROP TABLE groupe');
        $this->addSql('DROP TABLE inscription');
        $this->addSql('DROP TABLE jeune');
        $this->addSql('DROP TABLE maitrise');
        $this->addSql('DROP TABLE mouvement_entite');
        $this->addSql('DROP TABLE mouvement_groupe');
        $this->addSql('DROP TABLE mouvement_treso_activite');
        $this->addSql('DROP TABLE periode');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE responsable');
        $this->addSql('DROP TABLE responsable_formation');
        $this->addSql('DROP TABLE rubrique');
        $this->addSql('DROP TABLE rubrique_budget');
        $this->addSql('DROP TABLE sens_rubrique');
        $this->addSql('DROP TABLE session_formation');
        $this->addSql('DROP TABLE session_formation_responsable');
        $this->addSql('DROP TABLE sous_rubrique');
        $this->addSql('DROP TABLE tresorerie_activite');
        $this->addSql('DROP TABLE type_document');
        $this->addSql('DROP TABLE type_mouvement');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE utilisateur');
    }
}
