name: gestiscout
services:    
    db:
        image: postgres:15
        restart: always
        container_name: postgres_database
        environment:
            POSTGRES_PASSWORD: "root"
            POSTGRES_DB: gestiscout_db
            POSTGRES_USER: symfony
        ports:
        - "5432:5432"
        volumes:
        - pg_data:/var/lib/postgresql/data
        # networks:
        # - backend
    
    app:
        container_name: symfony_app_gestiscout
        build: 
            context: ..
            dockerfile: docker/Dockerfile
        depends_on:
        - db
        volumes:
        - ../:/var/www
        ports:
        - "8000:8081"
        # environment:
        #     DATABASE_URL: mysql://symfony:@db:3306/atelierdigital_db
        # networks:
        # - backend
        # - frontend
   
volumes:
    pg_data:

