index:
    path: /
    controller: App\Controller\LoginCustomController::login
configuration:
    path: /configuration
    controller: App\Controller\ConfigurationController::index
ListeAnnePastorale:
    path: /ListeAnnePastorale
    controller: App\Controller\ConfigurationController::ListeAnnePastorale
GetListeAnnee:
    path: /GetListeAnnee
    controller: App\Controller\ConfigurationController::GetListeAnnee
AddAnnee:
    path: /AddAnnee
    controller: App\Controller\ConfigurationController::AddAnnee
ListeFonction:
    path: /ListeFonction
    controller: App\Controller\ConfigurationController::ListeFonction
AddFonction:
    path: /AddFonction
    controller: App\Controller\ConfigurationController::AddFonction
GetListeFonction:
    path: /GetListeFonction
    controller: App\Controller\ConfigurationController::GetListeFonction
GetListBranche:
    path: /GetListBranche
    controller: App\Controller\ConfigurationController::GetListBranche
ListeBranche:
    path: /ListeBranche
    controller: App\Controller\ConfigurationController::ListeBranche
AddBranche:
    path: /AddBranche
    controller: App\Controller\ConfigurationController::AddBranche
Groupe:
    path: /Groupe
    controller: App\Controller\ConfigurationController::Groupe
AddGroupe:
    path: /AddGroupe
    controller: App\Controller\ConfigurationController::AddGroupe
GetAnneePastoraleUnique:
    path: /GetAnneePastoraleUnique
    controller: App\Controller\ConfigurationController::GetUniqueAnneePastorale
GetListGroupe:
    path: /GetListGroupe
    controller: App\Controller\ConfigurationController::GetListGroupe
GetListeGenre:
    path: /GetListeGenre
    controller: App\Controller\ConfigurationController::GetListeGenre
connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index
Dashboard:
    path: /Dashboard
    controller: App\Controller\ConnexionController::Dashboard
app_login:
    path: /login
    controller: App\Controller\LoginCustomController::login
DistrictDash:
    path: /DistrictDash
    controller: App\Controller\ConnexionController::DashboardDistrict
cotisation:
    path: /cotisation
    controller: App\Controller\CotisationController::index
cotisationResponsable:
    path: /cotisationResponsable
    controller: App\Controller\CotisationController::indexCotisationResponsable
ViewJeuneCotise:
    path: /ViewJeuneCotise
    controller: App\Controller\CotisationController::ViewJeuneCotise
ViewResponsableCotise:
    path: /ViewResponsableCotise
    controller: App\Controller\CotisationController::ViewResponsableCotise
cotisationJeune:
    path: /cotisationJeune
    controller: App\Controller\CotisationController::CotisationJeune
SaveCotisation:
    path: /SaveCotisation
    controller: App\Controller\CotisationController::SaveCotisation
GetListJeuneCotise:
    path: /GetListJeuneCotise
    controller: App\Controller\CotisationController::GetListJeuneCotise
GetListeJeuneCotiseParGroupe:
    path: /GetListeJeuneCotiseParGroupe
    controller: App\Controller\CotisationController::GetListeJeuneCotiseParGroupe
GetListeRespoNonCotise:
    path: /GetListeRespoNonCotise
    controller: App\Controller\CotisationController::GetListeRespoNonCotise
SaveCotisationResponsable:
    path: /SaveCotisationResponsable
    controller: App\Controller\CotisationController::SaveCotisationResponsable
GetListeRespoCotise:
    path: /GetListeRespoCotise
    controller: App\Controller\CotisationController::GetListeRespoCotise
district:
    path: /district
    controller: App\Controller\DistrictController::index
VueEnregistrement:
    path: /VueEnregistrement
    controller: App\Controller\DistrictController::VueEnregistrement
ListeJeuneDistrict:
    path: /ListeJeuneDistrict
    controller: App\Controller\DistrictController::ListeJeuneDistrict
ListeResponsableDistrict:
    path: /ListeResponsableDistrict
    controller: App\Controller\DistrictController::ListeResponsableDistrict
JeuneCotiseDistrict:
    path: /ListeJeuneCotise
    controller: App\Controller\DistrictController::ListeJeuneCotise
RechercheJeuneByCriteria:
    path: /RechercheJeuneByCriteria
    controller: App\Controller\DistrictController::RechercheJeuneByCriteria
RechercheResponsable:
    path: /RechercheResponsable
    controller: App\Controller\DistrictController::RechercheResponsableByCriteria
RechercheCotise:
    path: /RechercheCotise
    controller: App\Controller\DistrictController::RechercheCotiseDistrictByCriteria    
ListeResponsable_District:
    path: /ListeResponsable_District
    controller: App\Controller\DistrictController::ListeResponsable_District        
ListeResponsableCotiseDistrict:
    path: /ListeResponsableCotiseDistrict
    controller: App\Controller\DistrictController::ListeResponsableCotiseDistrict        
ListeMembreDistrict:
    path: /ListeMembreDistrict
    controller: App\Controller\DistrictController::ListeMembreDistrict    
AddResponsableDistrict:
    path: /AddResponsableDistrict
    controller: App\Controller\DistrictController::AddResponsableDistrict    
InsertRespoDistrict:
    path: /InsertRespoDistrict
    controller: App\Controller\DistrictController::InsertRespoDistrict    
jeune:
    path: /jeune
    controller: App\Controller\JeuneController::index        
ListeJeunes:
    path: /ListeJeunes
    controller: App\Controller\JeuneController::ListeJeunes   
success:
    path: /success
    controller: App\Controller\JeuneController::success   
error:
    path: /error
    controller: App\Controller\JeuneController::error   
ListeJeune:
    path: /ListeJeune
    controller: App\Controller\JeuneController::ListeJeune   
ListeJeuneNonCotise:
    path: /ListeJeuneNonCotise
    controller: App\Controller\JeuneController::ListeJeuneNonCotise
AddJeune:
    path: /AddJeune
    controller: App\Controller\JeuneController::AddJeune
AddJeuneFunction:
    path: /AddJeuneFunction
    controller: App\Controller\JeuneController::AddJeuneFunction
DeleteJeune:
    path: /DeleteJeune
    controller: App\Controller\JeuneController::DeleteJeune
GetJeuneUnique:
    path: /GetJeuneUnique
    controller: App\Controller\JeuneController::GetJeuneUnique
ModifierJeune:
    path: /ModifierJeune
    controller: App\Controller\JeuneController::ModifierJeune
ImportData:
    path: /ImportData
    controller: App\Controller\JeuneController::ImportData
ImportJeune:
    path: /ImportJeune
    controller: App\Controller\JeuneController::ImportationJeune
rapport:
    path: /rapport
    controller: App\Controller\RapportController::rapport
# TotalJeuneByGroupe:
#     path: /TotalJeuneByGroupe
#     controller: App\Controller\RapportController::GetTotalJeune
# TotalJeuneByGroupe:
#     path: /TotalJeuneByGroupe
#     controller: App\Controller\RapportController::GetTotalJeuneByGroupe    
responsable:
    path: /responsable
    controller: App\Controller\ResponsableController::index    
AjouterRespoView:
    path: /AjouterRespoView
    controller: App\Controller\ResponsableController::AjouterRespoView    
GetListResponsable:
    path: /GetListResponsable
    controller: App\Controller\ResponsableController::GetListResponsable 
GetListResponsableDistrict:
    path: /GetListResponsableDistrict
    controller: App\Controller\ResponsableController::GetListResponsableDistrictActif 
AddResponsable:
    path: /AddResponsable
    controller: App\Controller\ResponsableController::AddResponsable 
supprimerResponsable:
    path: /supprimerResponsable
    controller: App\Controller\ResponsableController::supprimerResponsable 
GetRespoUnique:
    path: /GetRespoUnique
    controller: App\Controller\ResponsableController::GetRespoUnique 
ModifRespo:
    path: /ModifRespo
    controller: App\Controller\ResponsableController::ModifRespo 
AjouterRespocg:
    path: /AjouterRespocg
    controller: App\Controller\ResponsableController::AjouterRespocg 
ListeRespoCg:
    path: /ListeRespoCg
    controller: App\Controller\ResponsableController::ListeRespoCg 
utilisateur:
    path: /utilisateur
    controller: App\Controller\UtilisateurController::index 
Addutilisateur:
    path: /Addutilisateur
    controller: App\Controller\UtilisateurController::Addutilisateur 
AddUserFromDistrict:
    path: /AddUserFromDistrict
    controller: App\Controller\UtilisateurController::AddUserFromDistrict 
CreateActivite:
    path: /CreateActivite
    controller: App\Controller\ActiviteController::CreateActivite 
Activites:
    path: /Activites
    controller: App\Controller\ActiviteController::ListActivite 
ListActivites:
    path: /ListActivites
    controller: App\Controller\ActiviteController::ListActivites 

details:
    path: /details/{id}
    controller: App\Controller\ActiviteController::VwDetailsActivite 

AddDetails:
    path: /AddDetails
    controller: App\Controller\ActiviteController::AddDetails
ProgrammesByActivite:
    path: /ProgrammesByActivite/{id}
    controller: App\Controller\ActiviteController::ListProgramme
redirectToProgramme:
    path: /redirectToProgramme
    controller: App\Controller\ActiviteController::redirectToProgramme
ConsulterDetails:
    path: /ConsulterDetails/{id}/{district}
    controller: App\Controller\ActiviteController::ConsulterDetails
UpdateAnneePastorale:
    path: /UpdateAnneePastorale
    controller: App\Controller\ConfigurationController::UpdateAnneePastorale
GetBrancheUnique:
    path: /GetBrancheUnique
    controller: App\Controller\ConfigurationController::BrancheUnique
GetGroupeUnique:
    path: /GetGroupeUnique
    controller: App\Controller\ConfigurationController::GroupeUnique
UpdateGroupe:
    path: /UpdateGroupe
    controller: App\Controller\ConfigurationController::UpdateGroupe
ExportToExcel:
    path: /ExportToExcel
    controller: App\Controller\RapportController::ExportToExcel
ExportToExcelAttachment:
    path: /ExportToExcelAttachment
    controller: App\Controller\RapportController::ExportToExcelAttachment
ExportJeuneByGroupeToExcelAttachment:
    path: /ExportJeuneByGroupeToExcelAttachment
    controller: App\Controller\RapportController::ExportJeuneByGroupeToExcelAttachment
ExportResponsableByGroupeToExcelAttachment:
    path: /ExportResponsableByGroupeToExcelAttachment
    controller: App\Controller\RapportController::ExportResponsableByGroupeToExcelAttachment
ExportJeuneDistrict:
    path: /ExportJeuneDistrict/{groupe}/{branche}
    controller: App\Controller\RapportController::ExportJeuneDistrict
ExportResponsableDistrict:
    path: /ExportResponsableDistrict/{groupe}
    controller: App\Controller\RapportController::ExportResponsableDistrict
Formation:
    path: /Formation
    controller: App\Controller\ConfigurationController::Formation
AddFormation:
    path: /AddFormation
    controller: App\Controller\ConfigurationController::AddFormation
GetListeFormation:
    path: /GetListeFormation
    controller: App\Controller\ConfigurationController::GetListeFormation
UpdateRespoDistrict:
    path: /UpdateRespoDistrict
    controller: App\Controller\DistrictController::UpdateRespoDistrict
chefparformation:
    path: /chefparformation
    controller: App\Controller\FormationController::chefparformation
ListeChefByChef:
    path: /ListeChefByChef
    controller: App\Controller\FormationController::ListeChefByChef
PrevisionStage:
    path: /PrevisionStage
    controller: App\Controller\FormationController::PrevisionStage
GetNextParticpation:
    path: /GetNextParticpation
    controller: App\Controller\FormationController::GetNextParticpation
ActivitesByGroupe:
    path: /ActivitesByGroupe
    controller: App\Controller\ActiviteController::ActivitesByGroupe
ViewActivitesByGroupeDistrict:
    path: /ViewActivitesByGroupeDistrict
    controller: App\Controller\ActiviteController::ViewActivitesByGroupeDistrict
ActivitesByGroupeDistrict:
    path: /ActivitesByGroupeDistrict
    controller: App\Controller\ActiviteController::ActivitesByGroupeDistrict
DetailsActiviteDistrict:
    path: /DetailsActiviteDistrict/{id}
    controller: App\Controller\ActiviteController::DetailsActiviteDistrict
GetListDistrict:
    path: /GetListDistrict
    controller: App\Controller\ConfigurationController::GetListDistrict
IndexCommissariatDistrict:
    path: /IndexCommissariatDistrict
    controller: App\Controller\ConfigurationController::IndexCommissariatDistrict
AddDistrict:
    path: /AddDistrict
    controller: App\Controller\ConfigurationController::AddDistrict
connexionlogin:
    path: /connexionlogin
    controller: App\Controller\SecurityController::connexion
DecisionActivite:
    path: /DecisionActivite
    controller: App\Controller\ActiviteController::DecisionActivite
DashAdmin:
    path: /DashAdmin
    controller: App\Controller\ConnexionController::DashAdmin
GetDistrictUnique:
    path: /GetDistrictUnique
    controller: App\Controller\ConfigurationController::GetDistrictUnique
Soumettre:
    path: /SoumettreActivite
    controller: App\Controller\ActiviteController::SoumettreActivite
CreerSession:
    path: /CreerSessionFormation
    controller: App\Controller\FormationController::CreerSessionFormation
SaveSession:
    path: /SaveSession
    controller: App\Controller\FormationController::SaveSession
Sessions:
    path: /Sessions
    controller: App\Controller\FormationController::Sessions
ListePreparatoire:
    path: /ListePreparatoire
    controller: App\Controller\FormationController::ListePreparatoire
CreerListeParticipant:
    path: /CreerListeParticipant
    controller: App\Controller\FormationController::CreerListeParticipant
ListResponsableNextSession:
    path: /ListResponsableNextSession
    controller: App\Controller\FormationController::GetResponsableBy_nextSession
ConfirmerParticpation:
    path: /ConfirmerParticpation
    controller: App\Controller\FormationController::ConfirmerParticpation
ListeDefinitive:
    path: /ListeDefinitive
    controller: App\Controller\FormationController::ListeDefinitive
ExportListeDefinitiveStages:
    path: /ExportListeDefinitiveStages/{stage}
    controller: App\Controller\RapportController::ExportListeDefinitiveStages
update_groupe_new:
    path: /update_groupe_new
    controller: App\Controller\ConfigurationController::update_groupe_new
ListeTypeDocuments:
    path: /ListeTypeDocuments
    controller: App\Controller\ConfigurationController::ListeTypeDocuments
addDocuments:
    path: /addDocuments
    controller: App\Controller\ActiviteController::addDocuments
GetDocumentsByActivite:
    path: /GetDocumentsByActivite
    controller: App\Controller\ActiviteController::GetDocumentsByActivite
DownloadDocument:
    path: /DownloadDocument/{docid}
    controller: App\Controller\RapportController::DownloadDocument
ModifierResponsable:
    path: /ModifierResponsable
    controller: App\Controller\ResponsableController::UpdateResponsable
Caisse:
    path: /Caisse
    controller: App\Controller\CaisseController::index
CreerCaisse:
    path: /CreerCaisse
    controller: App\Controller\CaisseController::CreerCaisse
VwOperations:
    path: /VwOperations
    controller: App\Controller\CaisseController::VwOperations
ListeOperations:
    path: /ListeOperations
    controller: App\Controller\CaisseController::GetListeOperation
ListeMvt:
    path: /ListeMvt
    controller: App\Controller\CaisseController::GetListeTypeMouvement
SaveMvt:
    path: /SaveMvt
    controller: App\Controller\CaisseController::SaveMvt
Solde:
    path: /Solde
    controller: App\Controller\CaisseController::Solde
Periode:
    path: /Periode
    controller: App\Controller\ConfigurationController::Periode
GetListPeriode:
    path: /GetListPeriode
    controller: App\Controller\ConfigurationController::GetListPeriode
SavePeriode:
    path: /SavePeriode
    controller: App\Controller\ConfigurationController::SavePeriode
Rubrique:
    path: /Rubrique
    controller: App\Controller\ConfigurationController::Rubrique
SaveRubrique:
    path: /SaveRubrique
    controller: App\Controller\ConfigurationController::SaveRubrique
GetRubriques:
    path: /GetRubriques
    controller: App\Controller\ConfigurationController::GetListRubrique
SousRubrique:
    path: /SousRubrique
    controller: App\Controller\ConfigurationController::SousRubrique
GetSousRubriques:
    path: /GetSousRubriques
    controller: App\Controller\ConfigurationController::GetListSousRubrique
SaveSousRubrique:
    path: /SaveSousRubrique
    controller: App\Controller\ConfigurationController::SaveSousRubrique
Evenement:
    path: /Evenement
    controller: App\Controller\CaisseController::Evenement
GetEvenements:
    path: /GetEvenements
    controller: App\Controller\CaisseController::GetListEvenement
SaveEvent:
    path: /SaveEvent
    controller: App\Controller\CaisseController::SaveEvent
MouvementEvenement:
    path: /MouvementEvenement
    controller: App\Controller\CaisseController::MouvementEvenement
MouvementsByEvent:
    path: /MouvementsByEvent/{eventId}
    controller: App\Controller\CaisseController::MouvementsByEvent
SaveMvtEvent:
    path: /SaveMvtEvent/{eventId}
    controller: App\Controller\CaisseController::SaveMvtEvent
ListeRubrique:
    path: /ListeRubrique
    controller: App\Controller\CaisseController::ListeRubrique
ListeSousRubrique:
    path: /ListeSousRubrique/{id}
    controller: App\Controller\CaisseController::ListeSousRubrique
MouvementsByEventActivite:
    path: /MouvementsByEventActivite/{id}
    controller: App\Controller\CaisseController::MouvementsByEventActivite
SoldeByEvent:
    path: /SoldeByEvent/{id}
    controller: App\Controller\CaisseController::SoldeByEvent
StatutEvent:
    path: /StatutEvent/{id}
    controller: App\Controller\CaisseController::GetStatutEvenement
MouvementsCaisse:
    path: /MouvementsCaisse
    controller: App\Controller\CaisseController::MouvementsCaisse
GetMouvementCaisse:
    path: /GetMouvementCaisse
    controller: App\Controller\CaisseController::GetMouvementCaisse












